name: Deploy Cloudformation Stack through GitHub Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Deploy Cloudformation Stack
      - name: Deploy Cloudformation Stack
        run: |
          aws cloudformation deploy \
            --template-file template.yml \
            --stack-name TestLambdaFunction \
            --capabilities CAPABILITY_NAMED_IAM
